version: '3.8'

services:

    db:
      image: postgres:16.1
      container_name: db-citas
      restart: always
      volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        POSTGRES_DB: 'citas'
        POSTGRES_USER: 'servicecitas'
        POSTGRES_PASSWORD: 'citasmedicas'
      ports:
        - '5434:5432'