server:
  port: 4040

spring:
  application:
    name: api-gateway
  profiles:
    default: oauth2 #eureka-off, eureka-on, oauth2
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
