spring:
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "configserver:http://localhost:8888"

server:
  servlet:
    context-path: /report-ms
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

