server:
  port: 8081
  servlet:
    context-path: /appointment-service

spring:
  application:
    name: appointment-service
  profiles:
    default: prod
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5434/citas
    username: servicecitas
    password: citasmedicas
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
